
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ButtonCounter(

  //////////// CLOCK //////////
  input wire                   clk,
  input wire                   resetn,

  //////////// SEG7 //////////
  output wire [7:0]            HEX0,
  output wire [7:0]            HEX1,
  output wire [7:0]            HEX2,
  output wire [7:0]            HEX3,
  output wire [7:0]            HEX4,
  output wire [7:0]            HEX5,

  //////////// KEY //////////
  input  wire [1:0]            KEY
);

typedef enum logic [7:0] {
  ZERO  = 8'b11000000,
  ONE   = 8'b11111001,
  TWO   = 8'b10100100,
  THREE = 8'b10110000,
  FOUR  = 8'b10011001,
  FIVE  = 8'b10010010,
  SIX   = 8'b10000010,
  SEVEN = 8'b11111000,
  EIGHT = 8'b10000000,
  NINE  = 8'b10011000
} seg4num_e;

typedef enum logic [1:0] {
  IDLE           = 2'h0,
  WAITINGONCOUNT = 2'h1,
  UPDATE7SEG     = 2'h2
} sys_state_e;

sys_state_e sys_state, sys_state_nxt;

typedef enum logic {
  WAITING       = 1'h0,
  BUTTONPRESSED = 1'h1
} button_state_e ;

wire button1;
wire buttonReg1;
assign button1 = KEY[0];
wire button2;
wire button2_q;
assign button2 = KEY[1];

metastability_register_N #(
  .busWidth (1)
) metastab1 (
  .clk      (clk       ),
  .busIn    (button1   ),
  .busOut   (buttonReg1)
);

metastability_register_N #(
  .busWidth (1)
) metastab2 (
  .clk      (clk       ),
  .busIn    (button2   ),
  .busOut   (button2_q)
);


logic [19:0] counter, counter_nxt;
integer last_counter = 0;
integer i;
integer n;
integer j;


seg4num_e num [0:5];

assign HEX0 = num[0];
assign HEX1 = num[1];
assign HEX2 = num[2];
assign HEX3 = num[3];
assign HEX4 = num[4];
assign HEX5 = num[5];

wire [23:0] number;

//999999 is 20 bits

logic [3:0] seg [0:5];

logic startConv;
wire convdone;


Binary_to_BCD
#(
  .INPUT_WIDTH    (20),
  .DECIMAL_DIGITS (6)
) BCD (
  .i_Clock        (clk),
  .i_Binary       (counter),
  .i_Start        (startConv),
  //
  .o_BCD          (number),
  .o_DV           (convdone)
);

//=======================================================
//  Structural coding
//=======================================================

button_state_e button_state, button_state_nxt;

logic lastButton1;
logic lastButton2;

always_ff @(posedge clk or negedge resetn) begin
  if (resetn) begin

  end else begin
  end
end

always @(*) begin
    case(sys_state)
      IDLE :
      begin
        if(last_counter != counter)
        begin
          sys_state_nxt = WAITINGONCOUNT;
          startConv = 1'b1;
          // last_counter = counter;
        end
      end

      WAITINGONCOUNT :
      begin
        startConv = 1'b0;
        if(convdone)
          sys_state_nxt = UPDATE7SEG;
      end

      UPDATE7SEG :
      begin
        seg[0] = number[3:0];
        seg[1] = number[7:4];
        seg[2] = number[11:8];
        seg[3] = number[15:12];
        seg[4] = number[19:16];
        seg[5] = number[23:20];

        sys_state_nxt = IDLE;
      end
    endcase
end

always_ff @(posedge clk or negedge resetn) begin
  if (!resetn) begin
    sys_state_nxt <= IDLE;
  end else begin
    sys_state <= sys_state_nxt;
  end
end



always @(*)
begin
  case(button_state)
    `waiting :
    begin
      if(lastButton1 != buttonReg1)
      begin
        counter = counter + 1;
        stateButton <= `buttonPressed;
        if(counter > 999999)
          counter = 999999;
      end
      else if(lastButton2 != button2_q)
      begin
        counter = counter - 1;
        stateButton <= `buttonPressed;
        if(counter < 0)
          counter = 0;
      end

      lastButton1 <= buttonReg1;
      lastButton2 <= button2_q;

    end

    `buttonPressed :
    begin
      if(lastButton1 != buttonReg1)
      begin
        stateButton <= `waiting;
      end
      if(lastButton2 != button2_q)
      begin
        stateButton <= `waiting;
      end

      lastButton1 <= buttonReg1;
      lastButton2 <= button2_q;


    end
  endcase

end



always @(posedge clk or negedge resetn) begin
  if (!resetn) begin
    for (i = 0; i <= 5; i = i + 1)
      begin
        num[i] <= 8'hff;
      end
  end else begin
    for (n = 0; n <= 5; n = n + 1)
    begin
      case(seg[n])
        0 : num[n]       <=  `zero;
        1 : num[n]       <=    `one;
        2 : num[n]       <=   `two;
        3 : num[n]       <= `three;
        4 : num[n]       <=  `four;
        5 : num[n]       <=  `five;
        6 : num[n]       <=    `six;
        7 : num[n]       <= `seven;
        8 : num[n]       <= `eight;
        9 : num[n]       <=   `nine;
        default : num[n] <= 8'hx;
      endcase
    end
  end

end


endmodule

